# Generated by Django 4.2.26 on 2025-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name (e.g., Pending, In Progress, Completed)', max_length=50, unique=True)),
                ('hexa_color', models.CharField(help_text='Hexadecimal color code (e.g., #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
                'ordering': ['name'],
            },
        ),
    ]
